package assets

// Code generated by scripts/embedgen.go; DO NOT EDIT.

var assetSHA256 = map[string]string{
    "templates/default.tmpl": "0f98d50a1cad8648886f625083fb7accdecfd4953fafd97f5dc94ccb90281c8d",
    "templates/system.tmpl": "d1b3f13bd9d0a4f9e4546f1be3dffae249e01677f4e54336e10b0e8b93a73fea",
    "themes/dark.json": "82c2478fe0df44ed742ecf003f3bc0be87f50f6f7d024e3b486a758e257e8281",
    "themes/light.json": "16634feb37689dce01e1d922e4e7b84e04637d1de6517184d07a71ffe29909da",
}
