// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package assets

// Code generated by scripts/embedgen.go; DO NOT EDIT.

var assetSHA256 = map[string]string{
	"templates/default.tmpl": "0f98d50a1cad8648886f625083fb7accdecfd4953fafd97f5dc94ccb90281c8d",
	"templates/system.tmpl":  "d1b3f13bd9d0a4f9e4546f1be3dffae249e01677f4e54336e10b0e8b93a73fea",
	"themes/dark.json":       "82c2478fe0df44ed742ecf003f3bc0be87f50f6f7d024e3b486a758e257e8281",
	"themes/light.json":      "16634feb37689dce01e1d922e4e7b84e04637d1de6517184d07a71ffe29909da",
}
