name: Bug report
description: File a bug
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve the project!
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, Go version
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
