# Copyright 2025 The ai-chat-cli Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI
on:
  pull_request:
  push:
    branches: [dev]
    tags: ['v*']

env:
  GO_VERSION: '1.24'

jobs:
  unit-linux:
    runs-on: [self-hosted, Linux, X64, quality]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: CASE=1/1 ./scripts/test-slice.sh
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: cov-linux
          path: coverage.out

  # Windows and macOS test jobs temporarily removed

  quality:
    needs: [unit-linux]
    runs-on: [self-hosted, linux, quality]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/download-artifact@v4
        with:
          path: .
      - run: |
          go install github.com/wadey/gocovmerge@latest
          gocovmerge $(find . -name coverage.out) > coverage.out
          go tool cover -func=coverage.out
      - run: |
          pct=$(go tool cover -func=coverage.out | awk '/^total:/ {gsub("%","",$3);print $3}')
          [[ ${pct%.*} -ge 93 ]] || { echo "::error::coverage ${pct}% < 93"; exit 1; }

  security:
    needs: quality
    runs-on: [self-hosted, linux, quality]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: gosec ./...
      - run: govulncheck ./...
      - run: trivy fs --exit-code 1 --severity HIGH,CRITICAL .
      - run: addlicense -check $(go list -f '{{.Dir}}' ./...)

  build-linux:
    needs: security
    runs-on: [self-hosted, Linux, X64, quality]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: GOOS=linux GOARCH=amd64 make build
      - uses: actions/upload-artifact@v4
        with:
          name: bin-linux
          path: bin

  snapshot:
    needs: build-linux
    runs-on: [self-hosted, Linux, X64, quality]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: bin-linux
          path: dist/linux
      - run: |
          zip -r snapshot-${{ github.run_id }}.zip dist
      - uses: actions/upload-artifact@v4
        with:
          name: snapshot-${{ github.run_id }}
          path: snapshot-${{ github.run_id }}.zip

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [snapshot, quality]
    runs-on: [self-hosted, Linux, X64, quality]
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: bin-linux
          path: .
      - name: Sign binaries
        run: cosign sign --yes bin-linux
      - name: Verify Rekor
        run: rekor-cli search --artifact bin-linux | grep -q 'UUID'
      - uses: softprops/action-gh-release@v2
        with:
          files: bin-linux snapshot-*.zip

  docs:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docs
        run: make docs
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs
