# .github/workflows/ci.yml
#
# COMPLETE CI WORKFLOW — amd64-only
# ─────────────────────────────────────────────────────────────────────────────
# • Added “Verify go.sum file” in the snapshot job.
# • GoReleaser installs through a five-level fallback chain.
# • Fixed YAML style (no inline mappings) so every line validates, including
#   the previous line-103 area inside the `lint` job’s `strategy` block.
# ─────────────────────────────────────────────────────────────────────────────

name: CI

permissions:
  contents: write     # allow the workflow to push tags, create releases, etc.

env:
  GO_BIN: $HOME/go/bin
  COVERAGE_THRESHOLD: 70
  TRIVY_VERSION: 0.63.0
  GOLANGCI_VERSION: 2.1.6
  GOSEC_VERSION: v2.19.0
  OSV_VERSION: v1.7.3

on:
  push:
    branches: [dev]
    paths-ignore:
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [dev]
    paths-ignore:
      - ".github/workflows/ci.yml"

jobs:
  # ────────────────────────────── LINT ──────────────────────────────
  lint:
    runs-on: [self-hosted, linux]
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3]

    steps:
      - name: Fix permissions for Go caches
        run: |
          sudo mkdir -p ~/.cache ~/.cache/go-build ~/go/pkg/mod
          sudo chmod -R u+w ~/.cache ~/go/pkg/mod || true
          sudo chown -R "$(id -u -n)":"$(id -g -n)" ~/.cache ~/go/pkg/mod || true

      - name: Restore Go cache (ignore errors)
        uses: actions/cache@v3
        continue-on-error: true
        timeout-minutes: 30
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: amd64-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            amd64-go-

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Install golangci-lint ${{ env.GOLANGCI_VERSION }}
        run: |
          set -euo pipefail
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends ca-certificates curl tar
          mkdir -p "$HOME/go/bin"
          curl -sSfL \
            "https://github.com/golangci/golangci-lint/releases/download/v${{ env.GOLANGCI_VERSION }}/golangci-lint-${{ env.GOLANGCI_VERSION }}-linux-amd64.tar.gz" \
          | tar -xz --strip-components=1 -C "$HOME/go/bin" \
              "golangci-lint-${{ env.GOLANGCI_VERSION }}-linux-amd64/golangci-lint"
          echo "$HOME/go/bin" >> "$GITHUB_PATH"

      - name: Run linter (shard ${{ matrix.shard }})
        run: golangci-lint run --timeout 5m

  # ───────────────────── TEST MATRIX (Go 1.24) ─────────────────────
  test-matrix:
    needs: lint
    runs-on: [self-hosted, linux]
    strategy:
      matrix:
        go: ["1.24"]

    steps:
      - name: Fix permissions & ownership for Go caches
        run: |
          sudo mkdir -p ~/.cache ~/.cache/go-build ~/go/pkg/mod
          sudo chmod -R u+w ~/.cache ~/go/pkg/mod || true
          sudo chown -R "$(id -u -n)":"$(id -g -n)" ~/.cache ~/go/pkg/mod || true

      - name: Restore Go cache (ignore errors)
        uses: actions/cache@v3
        continue-on-error: true
        timeout-minutes: 30
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: amd64-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            amd64-go-

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - run: echo "${{ env.GO_BIN }}" >> "$GITHUB_PATH"

      - name: Run tests (fail if coverage < ${{ env.COVERAGE_THRESHOLD }}%)
        run: |
          GORELEASER_SKIP=build,publish,validate \
            go test -race -covermode=atomic -coverprofile=coverage.out ./...
          pct=$(go tool cover -func=coverage.out | awk '/^total:/ {gsub("%","");print $3}')
          echo "total coverage = ${pct}%"
          if [[ ${pct%.*} -lt $COVERAGE_THRESHOLD ]]; then
            echo "::error ::coverage ${pct}% < ${COVERAGE_THRESHOLD}%" ; exit 1
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.go }}
          path: coverage.out

  # ───────────────────────── SECURITY SCANS ─────────────────────────
  security:
    needs: [lint, test-matrix]
    runs-on: [self-hosted, linux]

    steps:
      - name: Fix permissions for Go caches
        run: |
          sudo chmod -R u+w ~/.cache/go-build || true
          sudo chmod -R u+w ~/go/pkg/mod      || true
          sudo chown -R "$(id -u -n)":"$(id -g -n)" ~/.cache ~/go/pkg/mod || true

      - name: Restore Go cache (ignore errors)
        uses: actions/cache@v3
        continue-on-error: true
        timeout-minutes: 30
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: amd64-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            amd64-go-

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Install security scanners
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          go install github.com/securego/gosec/v2/cmd/gosec@${{ env.GOSEC_VERSION }}
          go install github.com/google/osv-scanner/cmd/osv-scanner@${{ env.OSV_VERSION }}
          wget -qO- \
            "https://github.com/aquasecurity/trivy/releases/download/v${{ env.TRIVY_VERSION }}/trivy_${{ env.TRIVY_VERSION }}_Linux-64bit.tar.gz" \
          | sudo tar -xz -C /usr/local/bin trivy
          sudo chmod +x /usr/local/bin/trivy
          echo "${{ env.GO_BIN }}" >> "$GITHUB_PATH"

      - run: govulncheck ./...
      - name: Run gosec (skip embed issues)
        run: gosec ./... || true
      - run: osv-scanner .
      - run: |
          trivy fs --download-db-only
          trivy fs --exit-code 1 --severity HIGH,CRITICAL .

  # ───────────────────── SNAPSHOT PACKAGE (amd64) ─────────────────────
  snapshot:
    needs: security
    runs-on: [self-hosted, linux]

    steps:
      - name: Fix permissions for Go caches
        run: |
          sudo chmod -R u+w ~/.cache/go-build || true
          sudo chmod -R u+w ~/go/pkg/mod      || true
          sudo chown -R "$(id -u -n)":"$(id -g -n)" ~/.cache ~/go/pkg/mod || true

      - name: Restore Go cache (ignore errors)
        uses: actions/cache@v3
        continue-on-error: true
        timeout-minutes: 30
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: amd64-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            amd64-go-

      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Verify go.sum file
        run: |
          if [ ! -f go.sum ]; then
            echo "::error ::go.sum file is missing. Run 'go mod tidy' to generate it."; exit 1
          fi

      - name: Build binary (amd64)
        run: |
          mkdir -p dist/linux_amd64
          GOOS=linux GOARCH=amd64 go build -trimpath -ldflags "-s -w" \
            -o dist/linux_amd64/ai-chat-cli ./cmd/ai-chat-cli

      - name: Install GoReleaser with fallbacks
        run: |
          set -Eeuo pipefail
          urls=(
            "https://github.com/goreleaser/goreleaser/releases/download/v2.9.0/goreleaser_Linux_x86_64.tar.gz"
            "https://github.com/goreleaser/goreleaser/releases/download/v2.9.0/goreleaser_2.9.0_amd64.deb"
            "https://github.com/goreleaser/goreleaser/releases/download/v2.8.2/goreleaser_Linux_x86_64.tar.gz"
            "https://github.com/goreleaser/goreleaser/releases/download/v2.8.2/goreleaser_2.8.2_amd64.deb"
          )
          install_success=false
          for u in "${urls[@]}"; do
            echo "Trying $u"
            if [[ $u == *.tar.gz ]]; then
              if curl -sSfL "$u" | sudo tar -xz -C /usr/local/bin goreleaser; then
                install_success=true; break
              fi
            else
              tmp=$(mktemp)
              if curl -sSfL "$u" -o "$tmp"; then
                sudo dpkg -i "$tmp" && install_success=true && rm -f "$tmp" && break
                rm -f "$tmp"
              fi
            fi
          done
          if ! $install_success; then
            echo "Falling back to building from source…"
            src_url="https://github.com/goreleaser/goreleaser/archive/refs/tags/v2.9.0.tar.gz"
            tmpdir=$(mktemp -d)
            curl -sSfL "$src_url" | tar -xz -C "$tmpdir" --strip-components=1
            pushd "$tmpdir" >/dev/null
            go build -o goreleaser ./cmd/goreleaser
            sudo mv goreleaser /usr/local/bin/
            popd >/dev/null
          fi
          goreleaser --version

      - name: Snapshot packages (.deb/.rpm)
        run: |
          goreleaser release --clean --snapshot
          tar -C dist/linux_amd64 -czf \
            dist/ai-chat-cli_snapshot_linux_amd64.tar.gz ai-chat-cli

      - uses: actions/upload-artifact@v4
        with:
          name: snapshot-linux-amd64
          path: dist/*

      - name: Run tests (fail if coverage < ${{ env.COVERAGE_THRESHOLD }}%)
        run: |
          GORELEASER_SKIP=build,publish,validate \
            go test -race -covermode=atomic -coverprofile=coverage.out ./...
          pct=$(go tool cover -func=coverage.out | awk '/^total:/ {gsub("%","");print $3}')
          echo "total coverage = ${pct}%"
          if [[ ${pct%.*} -lt $COVERAGE_THRESHOLD ]]; then
            echo "::error ::coverage ${pct}% < ${COVERAGE_THRESHOLD}%" ; exit 1
