name: ci

###############################################################################
# Triggers
###############################################################################
on:
  pull_request:
  push:
    branches: [dev, '**/phase*']
    tags: ['v*.*.*']
  schedule:
    - cron: '0 2 * * *'          # nightly snapshot (UTC)
  workflow_dispatch:
    inputs:
      target:
        description: 'Run ONE job (leave blank for full pipeline)'
        required: false
        default: ""

###############################################################################
# Global settings
###############################################################################
permissions:
  contents: write
  packages: write
  id-token: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: 1.24.x
  CACHE_DIR: ${{ github.workspace }}/go-cache
  RUN_TARGET: ${{ github.event.inputs.target || '' }}

###############################################################################
# Continuous Integration
###############################################################################
jobs:

  # ────────────────────────── Unit tests ──────────────────────────
  unit:
    if: ${{ env.RUN_TARGET == '' || env.RUN_TARGET == 'unit' }}
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v4

      - run: ./scripts/preflight-ci.sh

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - run: echo "GOMAXPROCS=$(nproc)" >> "$GITHUB_ENV"

      - name: Unit tests (race + coverage)
        run: |
          if ! ls -1 **/*.go 2>/dev/null | grep -q .; then
            echo 'package main' > dummy.go
          fi
          go test -race -covermode=atomic -coverprofile=coverage-linux.out -tags unit ./...

      - uses: actions/upload-artifact@v4
        with:
          name: cov-linux
          path: coverage-linux.out

  # ────────────────────────── Quality gate ──────────────────────────
  quality:
    if: ${{ env.RUN_TARGET == '' || env.RUN_TARGET == 'quality' }}
    needs: unit
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v4

      - run: ./scripts/preflight-ci.sh

      - uses: actions/download-artifact@v4
        with:
          path: cov

      - name: Merge & enforce ≥93 % coverage
        run: |
          go install github.com/wadey/gocovmerge@latest
          PROFILES=$(find cov -type f -name '*.out' -o -name '*.cov')
          if [[ -z "$PROFILES" ]]; then
            echo "docs-only change — coverage = 100 %"; exit 0
          fi
          gocovmerge $PROFILES > all.cov
          pct=$(go tool cover -func all.cov | awk '/total:/ {gsub("%","");print $3}')
          echo "coverage=$pct"
          awk -v p="$pct" 'BEGIN {exit(p < 93)}'

      - run: golangci-lint run

  # ────────────────────────── Security scan ──────────────────────────
  security:
    if: ${{ env.RUN_TARGET == '' || env.RUN_TARGET == 'security' }}
    needs: quality
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v4

      - run: ./scripts/preflight-ci.sh

      - name: Ensure scripts executable
        run: find . -type f -name '*.sh' ! -executable -print -exec chmod +x {} +

      - run: gosec ./...

      - run: addlicense -check $(go list -f '{{.Dir}}' ./...)

      - run: GOOS=linux GOARCH=amd64 go build -o bin/ai-chat-cli-linux-amd64 .

      - name: govulncheck (retry once)
        run: |
          for i in 1 2; do
            govulncheck ./... && break || { echo "retry $i"; sleep 4; }
          done

      - uses: actions/cache@v4
        with:
          path: ~/.cache/trivy/db
          key: ${{ runner.os }}-trivy-db-${{ hashFiles('**/go.sum') }}

      - id: trivy
        run: trivy fs --severity HIGH,CRITICAL --exit-code 1 .
        continue-on-error: true

      - if: steps.trivy.outcome == 'failure'
        run: trivy fs --skip-db-update --severity HIGH,CRITICAL --exit-code 1 .

  # ────────────────────────── Build (linux/amd64) ──────────────────────────
  build-linux:
    if: ${{ env.RUN_TARGET == '' || env.RUN_TARGET == 'build-linux' }}
    needs: security
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v4

      - run: ./scripts/preflight-ci.sh

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - run: echo "GOMAXPROCS=$(nproc)" >> "$GITHUB_ENV"

      - run: GOOS=linux GOARCH=amd64 make build

      - run: govulncheck -mode=binary bin/ai-chat-cli-linux-amd64

      - run: goreleaser --clean --snapshot

      - uses: actions/upload-artifact@v4
        with:
          name: bin-linux
          path: bin/ai-chat-cli-linux-amd64

###############################################################################
# Continuous Delivery
###############################################################################

  snapshot:
    if: ${{ github.event_name == 'schedule' }}
    needs: build-linux
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v4

      - run: ./scripts/preflight-ci.sh

      - uses: actions/download-artifact@v4
        with:
          name: bin-linux
          path: dist

      - run: |
          zip -j snapshot-${{ github.run_id }}.zip dist/*
          syft packages dist -o spdx-json > sbom.json

      - uses: actions/upload-artifact@v4
        with:
          name: snapshot-${{ github.run_id }}
          path: snapshot-${{ github.run_id }}.zip

  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: [build-linux, quality, security]
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v4

      - run: ./scripts/preflight-ci.sh

      - name: Build static linux/amd64 binary
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 \
          go build -trimpath -ldflags "-s -w" -o dist/ai-chat-cli

      - name: Tarball installer
        run: |
          cat > dist/install.sh <<'EOS'
          #!/bin/sh
          install -m755 ai-chat-cli /usr/local/bin/ai-chat-cli
          echo "ai-chat-cli installed ✨"
          EOS
          chmod +x dist/install.sh
          tar -C dist -czf dist/ai-chat-cli-linux-amd64.tar.gz ai-chat-cli install.sh

      - name: Package .deb / .rpm
        run: |
          sudo gem install --no-document fpm
          VERSION="${GITHUB_REF_NAME#v}"
          fpm -s dir -t deb -n ai-chat-cli -v "$VERSION" --license Apache-2.0 \
              dist/ai-chat-cli=/usr/bin/ai-chat-cli
          fpm -s dir -t rpm -n ai-chat-cli -v "$VERSION" --license Apache-2.0 \
              dist/ai-chat-cli=/usr/bin/ai-chat-cli

      - run: syft file:dist/ai-chat-cli -o spdx-json > sbom-bin.json
      - run: sha256sum dist/ai-chat-cli > dist/ai-chat-cli.sha256
      - run: cosign sign --yes dist/ai-chat-cli*

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/ai-chat-cli-linux-amd64.tar.gz
            dist/ai-chat-cli_*_amd64.deb
            dist/ai-chat-cli-*x86_64.rpm
            dist/ai-chat-cli.sha256
            sbom-bin.json
            dist/ai-chat-cli*.sig

  docs:
    if: ${{ env.RUN_TARGET == '' || env.RUN_TARGET == 'docs' }}
    needs: release
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/preflight-ci.sh
      - run: make docs

  publish-artefacts:
    if: ${{ env.RUN_TARGET == '' || env.RUN_TARGET == 'publish-artefacts' }}
    needs: docs
    runs-on: [self-hosted, Linux, X64]
    environment: artefact-registry
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/preflight-ci.sh
      - uses: actions/download-artifact@v4
        with:
          name: bin-linux
          path: dist
      - run: echo "${{ secrets.SBOM_CONTENT }}" > dist/sbom.json || true
      - name: Push OCI artefact
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | \
            oras login --username ci --password-stdin ${{ secrets.REGISTRY_HOST }}
          oras push ${{ secrets.REGISTRY_HOST }}/ai-chat/cli:v${{ github.ref_name }} \
            dist/ai-chat-cli-linux-amd64:application/x-executable \
            dist/sbom.json:application/spdx+json

  deploy-staging:
    if: ${{ env.RUN_TARGET == '' || env.RUN_TARGET == 'deploy-staging' }}
    needs: publish-artefacts
    runs-on: [self-hosted, Linux, X64]
    environment:
      name: staging
      url: https://staging.ai-chat.internal
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/preflight-ci.sh
      - name: Pull artefact
        run: oras pull ${{ secrets.REGISTRY_HOST }}/ai-chat/cli:v${{ github.ref_name }} --output /tmp/cli
      - name: Helm upgrade
        run: |
          helm upgrade --install ai-chat-staging charts/ai-chat \
            --namespace ai-chat-staging \
            --set image.registry=${{ secrets.REGISTRY_HOST }} \
            --set image.tag=v${{ github.ref_name }}
      - run: |
          kubectl -n ai-chat-staging rollout status deploy/ai-chat
          ./infra/tests/smoke-staging.sh

  deploy-production:
    if: ${{ env.RUN_TARGET == '' || env.RUN_TARGET == 'deploy-production' }}
    needs: deploy-staging
    runs-on: [self-hosted, Linux, X64]
    environment:
      name: production
      url: https://ai-chat.internal
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/preflight-ci.sh
      - name: Pull artefact
        run: oras pull ${{ secrets.REGISTRY_HOST }}/ai-chat/cli:v${{ github.ref_name }} --output /tmp/cli
      - name: Helm upgrade
        run: |
          helm upgrade --install ai-chat charts/ai-chat \
            --namespace ai-chat \
            --set image.registry=${{ secrets.REGISTRY_HOST }} \
            --set image.tag=v${{ github.ref_name }}
      - run: kubectl -n ai-chat rollout status deploy/ai-chat
