name: CI
on:
  push:
    branches: [ dev, phase0/bootstrap ]
  pull_request:
    branches: [ dev ]
jobs:
  coverage-gate:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Install Tools
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          go install golang.org/x/tools/cmd/godoc@latest
      - name: Run Tests
        run: |
          go test -race -covermode=atomic -coverprofile=coverage.out ./...
          pct=$(go tool cover -func=coverage.out | awk '/^total:/ {gsub("%","");print $3}')
          if [ ${pct%.*} -lt 83 ]; then echo "::error::coverage < 83%" && exit 1; fi
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out
  security-scan:
    runs-on: self-hosted
    needs: coverage-gate
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Run gosec
        run: gosec ./...
  docs:
    runs-on: self-hosted
    needs: security-scan
    steps:
      - uses: actions/checkout@v4
      - name: Generate Docs
        run: |
          make docs
          git diff --exit-code
