name: CI
on:
  push:
    branches: [ dev, phase2/cross-shell ]
  pull_request:
    branches: [ dev ]

jobs:
  test-linux:
    runs-on: [self-hosted, linux]
    steps: &steps
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Cache
        uses: actions/cache@v3
        with:
          path: /var/cache/ai-chat-cli/go
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - run: make lint test
  test-macos:
    runs-on: [self-hosted, macOS]
    steps: *steps
  test-windows:
    runs-on: [self-hosted, windows]
    steps: *steps
  coverage-gate:
    runs-on: [self-hosted, linux]
    needs: test-linux
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - run: |
          go test -race -covermode=atomic -coverprofile=coverage.out ./...
          pct=$(go tool cover -func=coverage.out | awk '/^total:/ {gsub("%","");print $3}')
          if [ ${pct%.*} -lt 83 ]; then echo "::error::coverage < 83%" && exit 1; fi
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out
  security-scan:
    runs-on: [self-hosted, linux]
    needs: coverage-gate
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - run: gosec ./...
  docs:
    runs-on: [self-hosted, linux]
    needs: security-scan
    steps:
      - uses: actions/checkout@v4
      - name: Generate Docs
        run: |
          make docs
          git config --global user.name "Jamal Al-Sarraf"
          git config --global user.email "jalsarraf0@gmail.com"
          git add .
          git commit -m "Update generated documentation" || echo "No changes to commit"
