name: CI

env:
  GO_BIN: $HOME/go/bin
  COVERAGE_THRESHOLD: 70
  TRIVY_VERSION: 0.63.0
  GOLANGCI_VERSION: 2.1.6
  GOSEC_VERSION: v2.19.0
  OSV_VERSION: v1.7.3

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  lint:
    runs-on: [self-hosted, linux]
    steps:
      - name: Fix permissions
        run: chmod -R u+w ~/go/pkg/mod/ || true

      - name: Clean Go cache
        run: |
          rm -rf ~/.cache/go-build/* || true
          rm -rf ~/go/pkg/mod/*      || true

      - name: Restore Go cache (ignore errors)
        uses: actions/cache@v3
        continue-on-error: true
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: self-hosted-linux-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            self-hosted-linux-go-

      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Install golangci-lint ${{ env.GOLANGCI_VERSION }}
        shell: bash
        run: |
          set -euo pipefail
          apt-get update -qq || true
          apt-get install -y --no-install-recommends ca-certificates curl tar || true
          mkdir -p "$HOME/go/bin"
          chown -R "$(id -u -n)":"$(id -g -n)" "$HOME/go"
          curl -sSfL \
            "https://github.com/golangci/golangci-lint/releases/download/v${GOLANGCI_VERSION}/golangci-lint-${GOLANGCI_VERSION}-linux-amd64.tar.gz" \
          | tar -xz --strip-components=1 -C "$HOME/go/bin" \
              "golangci-lint-${GOLANGCI_VERSION}-linux-amd64/golangci-lint"
          echo "$HOME/go/bin" >> "$GITHUB_PATH"

      - name: Run linter
        run: golangci-lint run --timeout 5m

  test-go-1-24:
    needs: lint
    runs-on: [self-hosted, linux]
    steps:
      - name: Fix permissions
        run: chmod -R u+w ~/go/pkg/mod/ || true

      - name: Clean Go cache
        run: |
          rm -rf ~/.cache/go-build/* || true
          rm -rf ~/go/pkg/mod/*      || true

      - name: Restore Go cache (ignore errors)
        uses: actions/cache@v3
        continue-on-error: true
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: self-hosted-linux-go-1.24-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            self-hosted-linux-go-1.24-

      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - run: echo "${GO_BIN}" >> "$GITHUB_PATH"

      - name: Run tests (fail if coverage < ${{ env.COVERAGE_THRESHOLD }}%)
        run: |
          GORELEASER_SKIP=build,publish,validate \
            go test -race -covermode=atomic -coverprofile=coverage.out ./...
          pct=$(go tool cover -func=coverage.out | awk '/^total:/ {gsub("%","");print $3}')
          echo "total coverage = ${pct}%"
          if [[ ${pct%.*} -lt $COVERAGE_THRESHOLD ]]; then
            echo "::error ::coverage ${pct}% < ${COVERAGE_THRESHOLD}%" ; exit 1
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: coverage-1.24
          path: coverage.out

  security:
    needs: [lint, test-go-1-24]
    runs-on: [self-hosted, linux]
    steps:
      - name: Fix permissions
        run: chmod -R u+w ~/go/pkg/mod/ || true

      - name: Clean Go cache
        run: |
          rm -rf ~/.cache/go-build/* || true
          rm -rf ~/go/pkg/mod/*      || true

      - name: Restore Go cache (ignore errors)
        uses: actions/cache@v3
        continue-on-error: true
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: self-hosted-linux-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            self-hosted-linux-go-

      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Install scanners
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          go install github.com/securego/gosec/v2/cmd/gosec@${GOSEC_VERSION}
          go install github.com/google/osv-scanner/cmd/osv-scanner@${OSV_VERSION}
          wget -qO- https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz \
            | tar -xzO trivy > /usr/local/bin/trivy
          chmod +x /usr/local/bin/trivy
          chown "$(id -u -n):$(id -g -n)" /usr/local/bin/trivy
          echo "${GO_BIN}" >> "$GITHUB_PATH"

      - run: govulncheck ./...
      - run: gosec ./...
      - run: osv-scanner .
      - run: |
          trivy fs --download-db-only
          trivy fs --exit-code 1 --severity HIGH,CRITICAL .

  snapshot-amd64:
    needs: security
    runs-on: [self-hosted, linux]
    steps:
      - name: Fix permissions
        run: chmod -R u+w ~/go/pkg/mod/ || true

      - name: Clean Go cache
        run: |
          rm -rf ~/.cache/go-build/* || true
          rm -rf ~/go/pkg/mod/*      || true

      - name: Restore Go cache (ignore errors)
        uses: actions/cache@v3
        continue-on-error: true
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: self-hosted-linux-go-amd64-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            self-hosted-linux-go-amd64-

      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Build binary
        env:
          GOARCH: amd64
        run: |
          mkdir -p dist/linux_${GOARCH}
          GOOS=linux GOARCH=${GOARCH} go build -trimpath -ldflags "-s -w" \
            -o dist/linux_${GOARCH}/ai-chat-cli ./cmd/ai-chat-cli

      - name: Install Goreleaser
        run: |
          curl -sSfL https://install.goreleaser.com/github.com/goreleaser/goreleaser@latest | sh -s -- -b /usr/local/bin

      - name: Snapshot packages (.deb/.rpm only for amd64)
        run: |
          goreleaser release --clean --snapshot --single-target \
            --id deb --id rpm --dist dist
          tar -C dist/linux_${GOARCH} -czf \
            dist/ai-chat-cli_snapshot_linux_${GOARCH}.tar.gz ai-chat-cli

      - uses: actions/upload-artifact@v4
        with:
          name: snapshot-linux-amd64
          path: dist/*

      - name: Run tests (fail if coverage < ${{ env.COVERAGE_THRESHOLD }}%)
        shell: bash
        run: |
          GORELEASER_SKIP=build,publish,validate \
            go test -race -covermode=atomic -coverprofile=coverage.out ./...
          pct=$(go tool cover -func=coverage.out | awk '/^total:/ {gsub("%","");print $3}')
          echo "total coverage = ${pct}%"
          if [[ ${pct%.*} -lt $COVERAGE_THRESHOLD ]]; then
            echo "::error ::coverage ${pct}% < ${COVERAGE_THRESHOLD}%" ; exit 1
          fi

  snapshot-arm64:
    needs: security
    runs-on: [self-hosted, linux]
    steps:
      - name: Fix permissions
        run: chmod -R u+w ~/go/pkg/mod/ || true

      - name: Clean Go cache
        run: |
          rm -rf ~/.cache/go-build/* || true
          rm -rf ~/go/pkg/mod/*      || true

      - name: Restore Go cache (ignore errors)
        uses: actions/cache@v3
        continue-on-error: true
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: self-hosted-linux-go-arm64-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            self-hosted-linux-go-arm64-

      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Build binary
        env:
          GOARCH: arm64
        run: |
          mkdir -p dist/linux_${GOARCH}
          GOOS=linux GOARCH=${GOARCH} go build -trimpath -ldflags "-s -w" \
            -o dist/linux_${GOARCH}/ai-chat-cli ./cmd/ai-chat-cli

      - name: Install Goreleaser
        run: |
          curl -sSfL https://install.goreleaser.com/github.com/goreleaser/goreleaser@latest | sh -s -- -b /usr/local/bin

      - name: Snapshot packages (tar.gz only for arm64)
        run: |
          tar -C dist/linux_${GOARCH} -czf \
            dist/ai-chat-cli_snapshot_linux_${GOARCH}.tar.gz ai-chat-cli

      - uses: actions/upload-artifact@v4
        with:
          name: snapshot-linux-arm64
          path: dist/*

      - name: Run tests (fail if coverage < ${{ env.COVERAGE_THRESHOLD }}%)
        shell: bash
        run: |
          GORELEASER_SKIP=build,publish,validate \
            go test -race -covermode=atomic -coverprofile=coverage.out ./...
          pct=$(go tool cover -func=coverage.out | awk '/^total:/ {gsub("%","");print $3}')
          echo "total coverage = ${pct}%"
          if [[ ${pct%.*} -lt $COVERAGE_THRESHOLD ]]; then
            echo "::error ::coverage ${pct}% < ${COVERAGE_THRESHOLD}%" ; exit 1
          fi
