# .github/workflows/release.yml
# ────────────────────────────────────────────────────────────────
# Publish Linux-amd64 tarball, .deb and .rpm whenever a version
# tag (v*) is pushed, or when triggered manually.

name: Release

on:
  push:
    tags: ['v*']          # e.g. v1.2.3
  workflow_dispatch:      # manual run button

jobs:
  release:
    runs-on: [self-hosted, linux]
    permissions:
      contents: write      # GoReleaser uploads assets via GitHub API
      packages: read

    strategy:
      matrix:
        os:   [linux]
        arch: [amd64]      # ARM intentionally skipped

    steps:
    # 1 ── Checkout ──────────────────────────────────────────────
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2 ── Cache Go modules & build cache ───────────────────────
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-

    # 3 ── Set up Go (version from go.mod) ──────────────────────
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    # 4 ── Run unit tests ───────────────────────────────────────
    - name: Run Go tests
      run: go test ./...

    # 5 ── GoReleaser: build & publish artefacts ────────────────
    - name: GoReleaser release
      uses: goreleaser/goreleaser-action@v5
      with:
        version: v2.10.2
        args: release --clean \
              --id deb --id rpm --dist dist \
              --skip=docker
